{
 "title": "Red Hat Data Grid Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Intro",
   "type": "text",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "# Red Hat Data Grid 8.1 Statistics\n![Drag Racing](https://www.redhat.com/cms/managed-files/red-hat-data-grid.svg)\n"
   }
  },
  {
   "title": "Time since start",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_stats_time_since_start",
     "legendFormat": "{{uptime}}"
    }
   ]
  },
  {
   "title": "Number of entries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "entries" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_stats_number_of_entries"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "evictions" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_stats_evictions",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Number of Entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_default_statistics_number_of_entries",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Grid Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "node(s)" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_health_number_of_nodes"
    }
   ]
  },
  {
   "title": "Average write time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_default_statistics_average_write_time",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Free Container Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_health_free_memory_kb",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cache Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_stats_data_memory_used",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}